### ISSUE TITLE
Desktop notifications aren't working

### ISSUE THREAD

**Issue by Mikaela** [flathub/org.squidowl.halloy#12]
Regardless of setting

```toml
[notifications.connected]
enabled = true
#mute = true
show_toast = true

[notifications.disconnected]
enabled = true
#mute = true
show_toast = true

[notifications.reconnected]
enabled = true
#mute = true
show_toast = true

[notifications.highlight]
enabled = true
#mute = true
show_toast = true
```

I was not seeing any notifications until migrating to the snap package for Halloy. I have a suspicion this is connected to Flatseal not displaying the notifications permission for portal for Halloy as being enabled.
